# Generated by Django 3.2.7 on 2021-10-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HVApp', '0004_auto_20211012_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojadevida',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
