# Generated by Django 3.2.7 on 2021-10-13 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HVApp', '0005_alter_hojadevida_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HojaDeVida',
        ),
    ]
