# Generated by Django 3.2.7 on 2021-10-13 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HVApp', '0006_delete_hojadevida'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaDeVida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=12)),
                ('Agnos_experiencia', models.CharField(max_length=3)),
                ('profesion', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HojaDeVida', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
